#!/bin/bash

psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} <<-EOSQL
    CREATE DATABASE ${AIRFLOW_POSTGRES_DB};
    CREATE USER $AIRFLOW_POSTGRES_USER WITH PASSWORD '${AIRFLOW_POSTGRES_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${AIRFLOW_POSTGRES_DB} TO ${AIRFLOW_POSTGRES_USER};

    CREATE DATABASE ${WARC_POSTGRES_DB};
    CREATE USER $WARC_POSTGRES_USER WITH PASSWORD '${WARC_POSTGRES_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${WARC_POSTGRES_DB} TO ${WARC_POSTGRES_USER};
EOSQL

psql -U ${WARC_POSTGRES_USER} -d ${WARC_POSTGRES_DB} <<-EOSQL
    CREATE TABLE IF NOT EXISTS web_crawling_urls (
      id SERIAL PRIMARY KEY,
      url VARCHAR(500),
      crawled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
EOSQL